# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esen.karaduman\PycharmProjects\DwFrictionFactor\DwFriction.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dw_Dialog(object):
    def setupUi(self, Dw_Dialog):
        Dw_Dialog.setObjectName("Dw_Dialog")
        Dw_Dialog.resize(290, 295)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dw_Dialog.sizePolicy().hasHeightForWidth())
        Dw_Dialog.setSizePolicy(sizePolicy)
        Dw_Dialog.setMaximumSize(QtCore.QSize(290, 295))
        Dw_Dialog.setAutoFillBackground(False)
        Dw_Dialog.setModal(False)
        self.widget = QtWidgets.QWidget(Dw_Dialog)
        self.widget.setGeometry(QtCore.QRect(15, 10, 258, 271))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.m_q = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_q.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.m_q.setMaximum(1000.0)
        self.m_q.setProperty("value", 2.0)
        self.m_q.setObjectName("m_q")
        self.gridLayout.addWidget(self.m_q, 0, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.m_d = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_d.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.m_d.setMaximum(1000.0)
        self.m_d.setProperty("value", 0.5)
        self.m_d.setObjectName("m_d")
        self.gridLayout.addWidget(self.m_d, 1, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.m_v = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_v.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.m_v.setDecimals(2)
        self.m_v.setMaximum(1000.0)
        self.m_v.setProperty("value", 1.0)
        self.m_v.setObjectName("m_v")
        self.gridLayout.addWidget(self.m_v, 2, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 4, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.m_e = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_e.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.m_e.setDecimals(6)
        self.m_e.setMaximum(1000.0)
        self.m_e.setProperty("value", 0.045)
        self.m_e.setObjectName("m_e")
        self.gridLayout.addWidget(self.m_e, 3, 2, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 2)
        self.cb_transition = QtWidgets.QComboBox(self.widget)
        self.cb_transition.setObjectName("cb_transition")
        self.cb_transition.addItem("")
        self.cb_transition.addItem("")
        self.gridLayout.addWidget(self.cb_transition, 4, 2, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 2)
        self.cb_turbulent = QtWidgets.QComboBox(self.widget)
        self.cb_turbulent.setObjectName("cb_turbulent")
        self.cb_turbulent.addItem("")
        self.cb_turbulent.addItem("")
        self.cb_turbulent.addItem("")
        self.gridLayout.addWidget(self.cb_turbulent, 5, 2, 1, 4)
        self.btn_ok = QtWidgets.QPushButton(self.widget)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 7, 1, 1, 2)
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 7, 3, 1, 3)
        self.te_result = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_result.sizePolicy().hasHeightForWidth())
        self.te_result.setSizePolicy(sizePolicy)
        self.te_result.setReadOnly(True)
        self.te_result.setObjectName("te_result")
        self.gridLayout.addWidget(self.te_result, 6, 0, 1, 6)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.m_d.raise_()
        self.m_v.raise_()
        self.m_e.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.btn_ok.raise_()
        self.btn_exit.raise_()
        self.label_9.raise_()
        self.cb_transition.raise_()
        self.label_10.raise_()
        self.cb_turbulent.raise_()
        self.te_result.raise_()
        self.btn_exit.raise_()

        self.retranslateUi(Dw_Dialog)
        self.cb_transition.setCurrentIndex(1)
        self.btn_exit.clicked.connect(Dw_Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dw_Dialog)

    def retranslateUi(self, Dw_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dw_Dialog.setWindowTitle(_translate("Dw_Dialog", "Dw-Sürtünme Katsayı"))
        self.label_5.setText(_translate("Dw_Dialog", "[m³/s]"))
        self.label_6.setText(_translate("Dw_Dialog", "[m]"))
        self.label_3.setText(_translate("Dw_Dialog", "Kinematik viskozite, v :"))
        self.m_v.setToolTip(_translate("Dw_Dialog", "1 centistokes = 1e-6 m²/s"))
        self.label_7.setText(_translate("Dw_Dialog", "[centistokes]"))
        self.label_4.setText(_translate("Dw_Dialog", "Yüzey pürüzlülük (e) :"))
        self.label_8.setText(_translate("Dw_Dialog", "[mm]"))
        self.label_9.setText(_translate("Dw_Dialog", "Geçiş akım yöntem :"))
        self.cb_transition.setItemText(0, _translate("Dw_Dialog", "Kübik interpolasyon"))
        self.cb_transition.setItemText(1, _translate("Dw_Dialog", "Swamee-jain"))
        self.label_10.setText(_translate("Dw_Dialog", "Türb. akım yöntem :"))
        self.cb_turbulent.setItemText(0, _translate("Dw_Dialog", "Colebrook-white"))
        self.cb_turbulent.setItemText(1, _translate("Dw_Dialog", "Swamee-jain"))
        self.cb_turbulent.setItemText(2, _translate("Dw_Dialog", "Halland"))
        self.btn_ok.setText(_translate("Dw_Dialog", "Hesapla"))
        self.btn_exit.setText(_translate("Dw_Dialog", "Çıkış"))
        self.label.setText(_translate("Dw_Dialog", "Debi, Q :"))
        self.label_2.setText(_translate("Dw_Dialog", "Çap, D :"))

